// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTracker.Data;
using VehicleTracker.Models;

namespace VehicleTracker.Migrations
{
    [DbContext(typeof(VehicleTrackerContext))]
    [Migration("25611205072232_add-timeofrecord-for-location")]
    partial class addtimeofrecordforlocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleTracker.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Latitude");

                    b.Property<decimal>("Longitude");

                    b.Property<DateTime>("TimeOfRecord");

                    b.Property<Guid>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Location");

                    b.HasData(
                        new { Id = new Guid("0e5cc4b8-4c97-4f8a-b0ef-46d76aeb1e98"), Latitude = 100m, Longitude = 200m, TimeOfRecord = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), VehicleId = new Guid("62d65fe9-35d2-4529-983e-d8f92441dfd8") }
                    );
                });

            modelBuilder.Entity("VehicleTracker.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new { Id = new Guid("62d65fe9-35d2-4529-983e-d8f92441dfd8"), Name = "Mercedes" }
                    );
                });

            modelBuilder.Entity("VehicleTracker.Models.Location", b =>
                {
                    b.HasOne("VehicleTracker.Models.Vehicle", "Vehicle")
                        .WithMany("Locations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
